### PR TITLE
IBX-2103: Bumped tedivm/stash requirement

### PR DESCRIPTION
**Pull request by mateuszdebinski**
Jira ticket: https://issues.ibexa.co/browse/IBX-2103

### CODE REVIEW

**Comment by konradoboza** [comment]
This is a potential BC break, yet I cannot see any breaking changes coming from the 0.17.0 (nor 0.17.1 which is the latest at the moment) release https://github.com/tedious/Stash/releases/tag/v0.17.0. Have you performed any basic sanities at least?

**Review by konradoboza — APPROVED** [review]
After internal sync and based on my previous comment, I think we should be good with this change, yet sanities would be welcome anyway.

**Review by webhdx — APPROVED** [review]
:+1: though this is indeed a BC break. This has to be clearly stated in upgrade guide.

**Review by micszo — APPROVED** [review]
Reproduced and retested on Ibexa DXP v3.3.19 with Stash v0.17.1.

**Review by damianz5 — APPROVED** [review]

**Pull request merged**
